/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './App.tsx'],
  theme: {
    extend: {
      colors: {
        mira: {
          primary: '#c96442',
          'primary-dark': '#a95034',
          'primary-disabled': '#e8e6dc',
          'on-primary': '#faf9f5',
          success: '#5db872',
          warning: '#d4a017',
          danger: '#c64545',
          'danger-light': '#fca5a5',
          muted: '#87867f',
          ink: '#141413',
          strong: '#252523',
          body: '#3d3d3a',
          soft: '#87867f',
          'bg-base': '#f5f4ed',
          'bg-subtle': '#e8e6dc',
          canvas: '#f5f4ed',
          card: '#faf9f5',
          'bg-input': '#faf9f5',
          'bg-bubble': '#e8e6dc',
          'text-base': '#141413',
          'text-ink': '#141413',
          'text-strong': '#252523',
          'text-body': '#3d3d3a',
          'text-secondary': '#5e5d59',
          'text-tertiary': '#87867f',
          'text-muted': '#87867f',
          'text-placeholder': '#87867f',
          border: '#e8e6dc',
          'border-light': '#f0eee6',
          'border-default': '#e8e6dc',
          'border-soft': '#f0eee6',
          'status-success': '#5db872',
          'status-warning': '#d4a017',
          'status-error': '#c64545',
          'status-error-bg': '#fce8e8',
          'accent-teal': '#5db8a6',
          'accent-amber': '#e8a55a',
          hint: '#e8e6dc',
          'hint-text': '#a95034',
          banner: '#e8e6dc',
          'banner-text': '#5e5d59',
        },
      },
      borderRadius: {
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '16px',
        'mira-xl': '20px',
        'mira-full': '9999px',
      },
      fontSize: {
        'mira-display-lg': ['64px', { lineHeight: '1.2' }],
        'mira-display-sm': ['40px', { lineHeight: '1.2' }],
        'mira-title-xl': ['28px', { lineHeight: '1.3' }],
        'mira-title-lg': ['20px', { lineHeight: '1.3' }],
        'mira-title-md': ['17px', { lineHeight: '1.3' }],
        'mira-body-md': ['16px', { lineHeight: '1.6' }],
        'mira-button': ['14px', { lineHeight: '1.3' }],
        'mira-caption': ['13px', { lineHeight: '1.5' }],
        'mira-caption-uppercase': ['12px', { lineHeight: '1.3' }],
        'mira-code': ['13px', { lineHeight: '1.5' }],
        'mira-xs': ['12px', { lineHeight: '16px' }],
        'mira-sm': ['13px', { lineHeight: '20px' }],
        'mira-base': ['14px', { lineHeight: '22px' }],
        'mira-md': ['15px', { lineHeight: '22px' }],
        'mira-lg': ['16px', { lineHeight: '24px' }],
        'mira-xl': ['17px', { lineHeight: '24px' }],
        'mira-2xl': ['18px', { lineHeight: '28px' }],
        'mira-3xl': ['20px', { lineHeight: '28px' }],
        'mira-4xl': ['28px', { lineHeight: '36px' }],
      },
      spacing: {
        'mira-xs': '4px',
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '16px',
        'mira-xl': '24px',
        'mira-section': '32px',
      },
    },
  },
  plugins: [],
};
